

# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMWWWWWWWMMKxdoookNMMMMMMMMMMMMMMMWWMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMWO:,,,;xWMK,   .kWMMMMWWMMMMMMWKd:kWKKMMXk:'dNXKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMK,    dMMN:   ,KMMMXkc;oKWMMN0:  ';.'kKo.  .:..dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMK,    dMMN:   ,KMNd.  ''.:OWMMx. ;c. .O0'  'l'  oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMK,    dMMN:   ,KMNd..xNd. '0MMx. dKc;dX0'  :Xd;oOKKXKXWMWkc:dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMK,    dMMWc   'kOkkdkNWx. .OMMx. dNXWMM0'  :XNWMWk,..lXM0, .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMXOK0,    dMMN:    ,;.,lcoKd  .OMMx. dMMMMM0'  ;XMMMMNl  ;XK; .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMWd'kK,    oWNk'   .kWO,  ;Xd  .OMMx. dMMMMM0'  ,KMMMMMK, .c, 'OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMXdlc.    .::;.   .kMN:  ,Kd  .kWMx. lWMMMM0'  '0MMMMMWd.   ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMNk'    ,xKNc   .xMMO.  :;  .lXNo. :XMMMWk'  'OMMMMMM0'  :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMX;    lWMN:   .xMMWx'.:,.'xNMWKOO0NMMMWKo;,;lONMMMXc  cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMX;    lWMN:   .xMMMWXXNKkKNNWMMMMMMMMMWk...,lk0KKO; .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMX;    lWMN:   .xMMMMMMx,''''dXOddKMMMMMNOolc::;,'..'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMWk.    ;KMN:   .xMMMMMMd     :d:,.'kWMMMMMMMMMWXK000XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMW0xxxddx0N0;   .oNMMMMMO.    cNWk. .lXMMMMMMMMMMMMMMMMKd0MMMMMKd0MMMMMMMMMMMMMMW00WMMMMMMMMMM
# MMMMMMMMMMMMMMMMWX0O00OKNMMMMMX;    lWMk.   :XMMMMMMMMMMMMMXo..kMMMXd..xMMMMMMMMMMMMXx;.:kodXMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWc    lWMk.   ;XMMMMMMMMMMN0o.  .:dkd'   ;dKMMMMWWMMMWXl. .,  ;KMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd    lWM0'   :NMMMNX0kKWMNkd'   ;ooo'   ,o0MNOo::dKWMMk. :0: .dWMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo.   cWMX;   oWKxc;;:;;xNWMN:  .kMMWl  .xMNx; ,o' .dNMk. :XOxKWMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc.    :kxd.  .OO.  cKNk..'xWN:  .kMMMl  .xWo   cNx. .kMk. :NMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo     c0c..;o0Wd   oWW0'  ;XN:  .kMMMl  .xNc   l0d;..xMk. :NMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.    cWWXXWMMWc   lNW0'  ;XN:  .kMMMl  .xX;   lNNNKKWMk. ;XMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;    lWMMMMMMWc   lNW0,  ,KN:  .OMMMl  .xX;   cWWKNMMMk. '0MMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx.  .oKWMMMMMMWl   lNW0'  .ON:  '0MMMl  .kWd.  :N0;lNMWkc;l0WMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo   .OMMMMMMMMMKo:'oNWO.  :KN:  ,KMMMo  '0MW0c..lc;OWMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.  .OMMMMMMMMMMMW0dool:oONMWc  ;XMMMo  '0MWWWXxokXMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  .OMMMMMMMMMMMMMWNNNMMMMMM0c,;kWMMKl,':k0xd0WMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo ,kXMMMMMMMMMMMMMMMMMMMMMMMMMWXKNMMMMWXOkO0KNMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.cWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNcoWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
# MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
